{% set version = "2.1.2" %}

package:
  name: bob.db.base
  version: {{ version }}

source:
  fn: bob.db.base-{{ version }}.zip
  url: https://pypi.io/packages/source/b/bob.db.base/bob.db.base-{{ version }}.zip
  md5: 485f11556b405bc537a95dc51b457439

build:
  entry_points:
    - bob_dbmanage.py = bob.db.base.script.dbmanage:main
  number: 0
  skip: true  # [win]
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - toolchain
    - setuptools
    - bob.extension
    - bob.io.base
    - sqlalchemy
    - six

  run:
    - python
    - bob.extension
    - bob.io.base
    - sqlalchemy
    - six

test:
  commands:
    - bob_dbmanage.py --help
    - nosetests -sv bob.db.base

  imports:
    - bob
    - bob.db
    - bob.db.base
    - bob.db.base.script

  requires:
    - nose

about:
  home: https://www.idiap.ch/software/bob/
  license: BSD 3-clause
  summary: Bob's Basic Database API

extra:
  recipe-maintainers:
    - 183amir
